version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    env_file:
      - .env.docker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
      - ./app/terraform_files:/app/app/terraform_files
      - ~/.ssh/dalgo_public_keys:/app/.ssh/dalgo_public_keys:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8006 --reload
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./app/terraform_files:/app/app/terraform_files
      - ~/.ssh/dalgo_public_keys:/app/.ssh/dalgo_public_keys:ro
    env_file:
      - .env.docker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.core.celery_app worker -Q terraform -l info
    restart: unless-stopped
    depends_on:
      - redis
      - api

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - .env.docker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ~/.ssh/dalgo_public_keys:/app/.ssh/dalgo_public_keys:ro
    command: celery -A app.core.celery_app flower --port=5555
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker

volumes:
  redis-data: 