version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=development_api_key
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app
      - /create-warehouse:/create-warehouse
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /create-warehouse:/create-warehouse
    environment:
      - API_KEY=development_api_key
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.core.celery_app worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
      - api

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - API_KEY=development_api_key
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.core.celery_app flower --port=5555
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker

volumes:
  redis-data: 